repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer

  - repo: local
    hooks:
      - id: isort
        name: "Formatting / Linting"
        language: system
        entry: ruff
        args: [check]
        files: \.py$
